
package com.itheima.ws.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.itheima.ws.service.User;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://service.ws.itheima.com/")
@XmlSeeAlso({
})
public interface UserService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "save", targetNamespace = "http://service.ws.itheima.com/", className = "com.itheima.ws.service.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://service.ws.itheima.com/", className = "com.itheima.ws.service.SaveResponse")
    public void save(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

}
